security:
  user:
    password: password   
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: flatland
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
server:
  port: 9999
  context-path: /uaa      