server:
  port: 0

spring:
  #oauth2:
  #  resource:
  #    userInfoUri: http://localhost:9999/uaa/user
  data:
    mongodb:
      database: invite
      host: localhost    

management:
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

  client:
    registryFetchIntervalSeconds: 5

logging:
  level:
    br.com.weparty: INFO
