
server:
  port: 0

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5

logging:
  level:
    com.weparty.core: INFO
    org.springframework.web: INFO


authserver:
    hostname: localhost
    port: 8899
    contextPath: userauth
    
spring:
  data:
    mongodb:
      database: teste
      host: localhost
  oauth2:
    resource: 
      userInfoUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/me
      preferTokenInfo: false 
    
